from .data_extraction_views import *
from .disease_prediction_views import *
from .disease_views import *
from .occupation_views import *
from .speciality_views import *
from .symptoms_views import *
from .treatment_category_views import *
from .treatment_views import *
from .user_views import *
