# Generated by Django 5.0.6 on 2024-07-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='contraindications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='indications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
